In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [ ]:
dataset = pd.read_csv('games_data_2fixx.csv')
dataset

id                             game  score  leaderbord  gamers  \
0        0               A Boy and His Blob    638        2.02    2194   
1        1                    A Hat in Time   1992        1.53    7062   
2        2              A Hero and a Garden   1364        1.01     503   
3        3         A Hero and a Garden (EU)   1363        1.01     581   
4        4  A King's Tale: Final Fantasy XV    637        2.02   21914   
...    ...                              ...    ...         ...     ...   
1579  1579         36 Fragments of Midnight   1367        1.06    8472   
1580  1580  36 Fragments of Midnight (Asia)   1335        1.03    2131   
1581  1581    36 Fragments of Midnight (EU)   1382        1.07   12273   
1582  1582            428: Shibuya Scramble   1943        1.47     916   
1583  1583       428: Shibuya Scramble (EU)   1917        1.45     718   

      comp_perc  rating  min_comp_time  max_comp_time recommend to play  
0          16.5     3.2             15             20       recommended  
1          35.9     4.2             15             20       recommended  
2          97.6     5.0              0              1       recommended  
3          97.8     2.9              0              1   not recommended  
4          14.1     3.3              4              5       recommended  
...         ...     ...            ...            ...               ...  
1579       82.3     2.5              0              1   not recommended  
1580       88.9     2.4              0              1   not recommended  
1581       79.2     2.4              0              1   not recommended  
1582       41.5     4.2             40             50       recommended  
1583       42.6     4.2             40             50       recommended  

[1584 rows x 10 columns]

In [ ]:
dataset_baru = dataset.loc[:,['game','score','gamers','rating','recommend to play']]
dataset_baru

game  score  gamers  rating recommend to play
0                  A Boy and His Blob    638    2194     3.2       recommended
1                       A Hat in Time   1992    7062     4.2       recommended
2                 A Hero and a Garden   1364     503     5.0       recommended
3            A Hero and a Garden (EU)   1363     581     2.9   not recommended
4     A King's Tale: Final Fantasy XV    637   21914     3.3       recommended
...                               ...    ...     ...     ...               ...
1579         36 Fragments of Midnight   1367    8472     2.5   not recommended
1580  36 Fragments of Midnight (Asia)   1335    2131     2.4   not recommended
1581    36 Fragments of Midnight (EU)   1382   12273     2.4   not recommended
1582            428: Shibuya Scramble   1943     916     4.2       recommended
1583       428: Shibuya Scramble (EU)   1917     718     4.2       recommended

[1584 rows x 5 columns]

In [ ]:
x = dataset_baru.loc[:, ['game','score','gamers','rating']].values
y = dataset_baru.loc[:, ['recommend to play']].values
print(x,y)

[[1.4000e+01 6.3800e+02 2.1940e+03 3.2000e+00]
 [1.5000e+01 1.9920e+03 7.0620e+03 4.2000e+00]
 [1.6000e+01 1.3640e+03 5.0300e+02 5.0000e+00]
 ...
 [1.1000e+01 1.3820e+03 1.2273e+04 2.4000e+00]
 [1.2000e+01 1.9430e+03 9.1600e+02 4.2000e+00]
 [1.3000e+01 1.9170e+03 7.1800e+02 4.2000e+00]] [['recommended']
 ['recommended']
 ['recommended']
 ...
 ['not recommended']
 ['recommended']
 ['recommended']]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset_baru['game'] = le.fit_transform(dataset['game'].values)
y = le.fit_transform(y)
print(dataset_baru)
print(y)

      game  score  gamers  rating recommend to play
0       14    638    2194     3.2       recommended
1       15   1992    7062     4.2       recommended
2       16   1364     503     5.0       recommended
3       17   1363     581     2.9   not recommended
4       18    637   21914     3.3       recommended
...    ...    ...     ...     ...               ...
1579     9   1367    8472     2.5   not recommended
1580    10   1335    2131     2.4   not recommended
1581    11   1382   12273     2.4   not recommended
1582    12   1943     916     4.2       recommended
1583    13   1917     718     4.2       recommended

[1584 rows x 5 columns]
[1 1 1 ... 0 1 1]


/usr/local/lib/python3.9/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
print(x,y)

[[1.4000e+01 6.3800e+02 2.1940e+03 3.2000e+00]
 [1.5000e+01 1.9920e+03 7.0620e+03 4.2000e+00]
 [1.6000e+01 1.3640e+03 5.0300e+02 5.0000e+00]
 ...
 [1.1000e+01 1.3820e+03 1.2273e+04 2.4000e+00]
 [1.2000e+01 1.9430e+03 9.1600e+02 4.2000e+00]
 [1.3000e+01 1.9170e+03 7.1800e+02 4.2000e+00]] [1 1 1 ... 0 1 1]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [ ]:
print(x_train)

[[2.2900e+02 1.4420e+03 1.7000e+03 3.4000e+00]
 [1.1930e+03 1.5810e+03 2.1660e+03 3.3000e+00]
 [7.7000e+01 2.6840e+03 1.4809e+04 3.3000e+00]
 ...
 [1.2260e+03 1.6890e+03 7.3734e+04 4.3000e+00]
 [5.7100e+02 4.0640e+03 3.3239e+04 3.1000e+00]
 [6.9200e+02 1.3560e+03 1.2140e+03 2.1000e+00]]


In [ ]:
print(x_test)

[[9.5700e+02 5.0100e+02 7.1450e+03 3.7000e+00]
 [1.0410e+03 1.3380e+03 1.1810e+03 1.0000e+00]
 [9.0100e+02 1.3750e+03 4.8069e+04 1.8000e+00]
 ...
 [7.5700e+02 3.8730e+03 3.2875e+04 3.4000e+00]
 [2.4400e+02 1.5610e+03 5.9430e+03 3.7000e+00]
 [4.1100e+02 5.8700e+02 5.0160e+04 2.8000e+00]]


In [ ]:
print(y_train)

[1 1 1 ... 1 1 0]


In [ ]:
print(y_test)

[1 0 0 0 0 1 0 0 1 0 1 1 1 1 0 0 1 0 1 1 0 1 0 0 1 0 0 0 1 1 1 0 0 1 1 0 1
 1 0 1 0 0 1 1 0 1 1 0 1 1 0 1 1 1 1 1 1 1 1 0 0 0 0 1 1 0 0 1 1 0 0 1 0 0
 1 1 1 1 1 1 1 1 0 1 0 1 0 1 1 0 1 1 0 1 1 1 0 0 0 0 1 0 0 0 0 1 1 1 1 0 1
 1 1 0 1 1 0 0 0 1 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 0 0 1 0 0 1 0 1 0 0 1 0 1
 0 0 0 0 0 0 1 1 1 1 0 1 1 0 1 1 0 1 1 1 1 0 1 1 0 1 1 0 0 1 1 1 1 0 1 1 1
 1 1 0 1 1 0 1 1 1 1 0 1 0 1 0 0 0 0 1 1 1 1 0 1 1 1 1 1 1 0 1 0 0 1 1 1 1
 1 0 1 0 0 1 0 0 0 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 0 0 0 1 1 0 0 1 1 0 0 1 1
 0 1 1 0 1 0 1 0 1 1 1 0 1 0 0 1 1 1 0 0 0 0 0 1 1 1 0 1 1 1 0 1 0 1 1 0 1
 0 1 0 1 1 1 1 1 1 0 0 1 0 1 1 0 1 0 1 1 0]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:5] = sc.fit_transform(x_train[:, 3:5])
x_test[:, 3:5] = sc.transform(x_test[:, 3:5])

In [ ]:
print(x_train)

[[ 2.29000000e+02  1.44200000e+03  1.70000000e+03  3.25815789e-01]
 [ 1.19300000e+03  1.58100000e+03  2.16600000e+03  2.24038519e-01]
 [ 7.70000000e+01  2.68400000e+03  1.48090000e+04  2.24038519e-01]
 ...
 [ 1.22600000e+03  1.68900000e+03  7.37340000e+04  1.24181121e+00]
 [ 5.71000000e+02  4.06400000e+03  3.32390000e+04  2.04839808e-02]
 [ 6.92000000e+02  1.35600000e+03  1.21400000e+03 -9.97288712e-01]]


In [ ]:
print(x_test)

[[ 9.57000000e+02  5.01000000e+02  7.14500000e+03  6.31147597e-01]
 [ 1.04100000e+03  1.33800000e+03  1.18100000e+03 -2.11683868e+00]
 [ 9.01000000e+02  1.37500000e+03  4.80690000e+04 -1.30262052e+00]
 ...
 [ 7.57000000e+02  3.87300000e+03  3.28750000e+04  3.25815789e-01]
 [ 2.44000000e+02  1.56100000e+03  5.94300000e+03  6.31147597e-01]
 [ 4.11000000e+02  5.87000000e+02  5.01600000e+04 -2.84847827e-01]]
