In [66]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [67]:
dataset = pd.read_csv('games_data_2fixx.csv')
dataset = dataset.drop('game', axis=1)
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values

In [68]:
dataset

id  score  leaderbord  gamers  comp_perc  rating  min_comp_time  \
0        0    638        2.02    2194       16.5     3.2             15   
1        1   1992        1.53    7062       35.9     4.2             15   
2        2   1364        1.01     503       97.6     5.0              0   
3        3   1363        1.01     581       97.8     2.9              0   
4        4    637        2.02   21914       14.1     3.3              4   
...    ...    ...         ...     ...        ...     ...            ...   
1579  1579   1367        1.06    8472       82.3     2.5              0   
1580  1580   1335        1.03    2131       88.9     2.4              0   
1581  1581   1382        1.07   12273       79.2     2.4              0   
1582  1582   1943        1.47     916       41.5     4.2             40   
1583  1583   1917        1.45     718       42.6     4.2             40   

      max_comp_time recommend to play  
0                20       recommended  
1                20       recommended  
2                 1       recommended  
3                 1   not recommended  
4                 5       recommended  
...             ...               ...  
1579              1   not recommended  
1580              1   not recommended  
1581              1   not recommended  
1582             50       recommended  
1583             50       recommended  

[1584 rows x 9 columns]

In [69]:
print(x)

[[0.000e+00 6.380e+02 2.020e+00 ... 3.200e+00 1.500e+01 2.000e+01]
 [1.000e+00 1.992e+03 1.530e+00 ... 4.200e+00 1.500e+01 2.000e+01]
 [2.000e+00 1.364e+03 1.010e+00 ... 5.000e+00 0.000e+00 1.000e+00]
 ...
 [1.581e+03 1.382e+03 1.070e+00 ... 2.400e+00 0.000e+00 1.000e+00]
 [1.582e+03 1.943e+03 1.470e+00 ... 4.200e+00 4.000e+01 5.000e+01]
 [1.583e+03 1.917e+03 1.450e+00 ... 4.200e+00 4.000e+01 5.000e+01]]


In [70]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [71]:
print(x)

  (0, 537)	1.0
  (0, 1488)	638.0
  (0, 1489)	2.02
  (0, 1490)	16.5
  (0, 1491)	3.2
  (0, 1492)	15.0
  (0, 1493)	20.0
  (1, 846)	1.0
  (1, 1487)	1.0
  (1, 1488)	1992.0
  (1, 1489)	1.53
  (1, 1490)	35.9
  (1, 1491)	4.2
  (1, 1492)	15.0
  (1, 1493)	20.0
  (2, 106)	1.0
  (2, 1487)	2.0
  (2, 1488)	1364.0
  (2, 1489)	1.01
  (2, 1490)	97.6
  (2, 1491)	5.0
  (2, 1493)	1.0
  (3, 129)	1.0
  (3, 1487)	3.0
  (3, 1488)	1363.0
  :	:
  (1580, 1491)	2.4
  (1580, 1493)	1.0
  (1581, 988)	1.0
  (1581, 1487)	1581.0
  (1581, 1488)	1382.0
  (1581, 1489)	1.07
  (1581, 1490)	79.2
  (1581, 1491)	2.4
  (1581, 1493)	1.0
  (1582, 252)	1.0
  (1582, 1487)	1582.0
  (1582, 1488)	1943.0
  (1582, 1489)	1.47
  (1582, 1490)	41.5
  (1582, 1491)	4.2
  (1582, 1492)	40.0
  (1582, 1493)	50.0
  (1583, 174)	1.0
  (1583, 1487)	1583.0
  (1583, 1488)	1917.0
  (1583, 1489)	1.45
  (1583, 1490)	42.6
  (1583, 1491)	4.2
  (1583, 1492)	40.0
  (1583, 1493)	50.0


In [79]:
from sklearn.model_selection import train_test_split
X_train, x_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [81]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

ValueError: ignored

In [75]:
y_pred = regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

NameError: ignored